### ISSUE TITLE
Questions about EpiDoc itself: help with schema or guidelines

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/Tutorials#1]
If you have questions about the very basics of using EpiDoc, including loading the Schema in your XML editor, using or understanding the EpiDoc QuickRefs or Guidelines, or other first-level EpiDoc resources, please ask them here, and we (or your colleagues) may be able to help. Give as much detail as possible of any technical issues or error messages.

**Comment by Dany71-Che** [comment]
I have a doubt of how to produce a copy of the Epi.Doc. Template. The link in the program brings me to a webpage: I have copied the content in a xml document I have opened in Oxygen XML Editor. Is this correct or there is another way to duplicate the Epi.Doc. Template?

**Comment by paregorios** [comment]
That should work. Or you can use your browser's "save page" functionality.

**Comment by PietroLiuzzo** [comment]
I do not know which is the file you copied. in principle copy pasting a file from an existing one to start can be a good way to get started and your described way of doing so sound ok. Oxygen, once you save with extension .xml your file, if there is a processing instruction linked to the EpiDoc schema at the top of your file will also validate immediately. if no processing instruction is present, I think it will try to validate to a generic TEI schema based on the namespace.

**Comment by IreneVagionakis** [comment]
If the link you are referring to is https://epidoc.stoa.org/gl/latest/ex-epidoctemplate.xml?format=raw, the best approach is to download it by right-clicking on the page and selecting "Save as"/"Save page as", but it should work also as you did, as the file has the links to the EpiDoc schema at its top.

**Comment by Dany71-Che** [comment]
Thank you very much to all three!

**Comment by kruschwitzp** [comment]
Hi all – I've been trying to encode an inscription that presents itself as a mixture of prose and verse elements. I've watched the general encoding and the verse inscriptions encoding tutorials (brilliant stuff!), but I remain a bit unclear as to how to proceed when an inscription contains two distinctive parts. Should I just use` <ab>` for the prose part and `<lg> `for the verse part then? And how does that sit with the attribution of line numbers (for the inscription, I mean, not the XML document)?

**Comment by PietroLiuzzo** [comment]
My instinct would be to process ingredients separately instead of approaching it as a mix to begin with. I would add `<lg>` where there is an `<lg>` and a `<l>` or a `<seg>` where they are relevant. When all is child of an `<ab>` what is not explicitly marked as verse, is not such = is prose, and you block effectively contains a mixture of prose and verse. Perhaps this example here is fitting? https://igcyr.unibo.it/igcyr/gvcyr052.xml

**Comment by IreneVagionakis** [comment]
If the prose part can be considered semantically distinct from the verse part, you can also use two separate `<div type="textpart">`, and then use `<ab>` for the former and `<lg>` for the latter. Othwerwise, if the two parts are one after the other, you can do as you said, that is using `<ab>` for the prose and `<lg>` for the verse. If the prose and verse lines are mixed, instead, you can do as Pietro wrote.
In any case, the line numbering won't be an issue, because you can continue to number the `<lb/>`s progressively (so, e.g., you can have  `<ab>
      <lb n="1"/>...
      <lb n="2"/>...
</ab>
<lg>
      <l><lb n="3"/>... <lb n="4"/>...</l>
</lg>`)

**Comment by EPiette94** [comment]
Hi everyone,
I have a small question concerning Oxygen: in a introductive video, Gabby talked about a shortcut to copy paste every time the same element (cmd+/ on an English Mac keyboard). I can't find the equivalent on a Belgian (FN) Mac keyboard. 
<img width="386" alt="Capture d’écran 2021-04-13 à 15 22 34" src="https://user-images.githubusercontent.com/81029833/114560497-0d185980-9c6d-11eb-949e-843bea81a571.png">
Does anybody know which one it would be?
Thanks in advance

**Comment by gabrielbodard** [comment]
@EPiette94 If you go to the "Document" menu in Oxygen, and select the "Markup" dropdown, the first item in that submenu should offer to repeat your last action (in mine it says "Surround with <surplus>   ⌘/") ; hopefully that will tell you what the keyboard shortcut will be?

(If not, the '/' on my keyboard is where the '=' key is on the character map you shared. Worth a try?)

**Comment by PietroLiuzzo** [comment]
<img width="994" alt="Schermata 2021-04-13 alle 15 33 46" src="https://user-images.githubusercontent.com/508012/114564362-88c7d580-9c70-11eb-85d2-26ec519aed11.png">
perhaps also the shortcut menu in oxygen can be a good place to look at. there you should be able to set your own shortcuts

**Comment by EPiette94** [comment]
@gabrielbodard Quite strange, but while I also had "Surround with ⌘/" in the menu, it didn't work. But I've changed the shortcut in the board given by @PietroLiuzzo and now it works, so problem solved!
Thank to both of you.

**Comment by PietroLiuzzo** [comment]
If you like keyboard shortcuts, have a look also at Code Templates above in the oxygen preferences. It can save a lot of encoding time to be able to select and hit a combination of keys to enter XML fragments which are already structured, for figures for example, or choice elements, or recurring types of gaps, abbreviations, etc. I use the same tools also for example to add unicode which is not easy to key in (ethiopic and ethiopic transcription, standard sequences, etc.)

**Comment by gabrielbodard** [comment]
@EPiette94 : I guess the Oxygen setup is still expecting the US keyboard. I should have thought of that. Sorry! At least you could customize it yourself. :)

**Comment by EPiette94** [comment]
> @EPiette94 : I guess the Oxygen setup is still expecting the US keyboard. I should have thought of that. Sorry! At least you could customize it yourself. :)

Don't worry, and you're right, it's even better so with some kind of customization :)

**Comment by DaliaPM** [comment]
Hello! can we repeat here please how to use Oxygen the way that the whole text is displayed on the screen, so that we don't have to scroll on the sides? thanks!

**Comment by IreneVagionakis** [comment]
You can do it from Preferences > Editor > Edit modes > Text > Line wrap

**Comment by camillacampedelli** [comment]
@IreneVagionakis sorry for writing earlier in the wrong forum: again about the schema: typing the link from the video, I just get only what I showed you in the screenshot

**Comment by gabrielbodard** [comment]
The safest way to download either the EpiDoc schema or the EpiDoc template is to right-click (or ctrl-click on Mac, or 2-finger-tap on a trackpad) on the link (in the programme, reproduced below) and select "Save link as..." from the dropdown menu. This removes the risk of copying unwanted characters from the page, or the browser trying to save it as HTML, ecc.

> Files to download and copy (right-click on the link and "save link as…"):
> * [EpiDoc Template](https://epidoc.stoa.org/gl/latest/ex-epidoctemplate.xml?format=raw) 
> * [EpiDoc Schema](https://epidoc.stoa.org/schema/latest/tei-epidoc.rng)
