### ISSUE TITLE
Verse Inscriptions: Line visualisation in Diplomatic version EFES

### ISSUE THREAD

**Issue by dmurzea** [EpiDoc/Tutorials#10]
How can I display in the **Diplomatic version** just the line breaks and not the verse division as in the **Interpretive version**?

**Comment by IreneVagionakis** [comment]
It requires some quite advanced customisation of EFES!
You will need to edit the template that you are using or create a new one (https://github.com/EpiDoc/EFES/wiki/Creating-a-new-edition-structure-template) and define in it that you want the metrical display only in the interpretive edition.

**Comment by gabrielbodard** [comment]
Actually, this ought to be the default behaviour of the diplomatic display, and I was a bit surprised that it wasn't. I have checked the XSLT for the display that EFES uses, and as far as I can see, it (a) should be ignoring verse-lines in the diplomatic view; and (b) it should be offering you a third view "verse" if there is an `<lg>` in your edition.

In any case, this is a bug that we should fix in EFES, not something that you need to create a new view for…
