### ISSUE TITLE
EFES display

### ISSUE THREAD

**Issue by enabney** [EpiDoc/Tutorials#11]
EFES is working fine for me, so this isn't a major issue, but I was wondering whether there's an easy way to get texts to display in DDbDP style rather than the default Panciera style? It will make it a bit easier to check the papyri I'm working on.

**Comment by IreneVagionakis** [comment]
There is a configuration file in EFES folder, webapps/ROOT/sitemaps/config.xmap, where at line 87 there is the parameter `<epidoc-leiden-style>panciera</epidoc-leiden-style>` in which you can replace 'panciera' with 'ddbdp'. You can find a list of the other supported values in webapps/ROOT/kiln/stylesheets/epidoc/README.txt.
If the config.xmap file is not opened by default with Oxygen, you can drag it inside the Oxygen window or right-click it, select 'Open with' and then select 'Oxygen XML Editor'.

**Comment by LauraNast** [comment]
Hi, sorry to jump in but I have a question about the EFES display too. I have changed the setting as explained in the Q&A session but I still cannot see my internal apparatus. Is there something else I could do to check whether I did it right? 
Thanks!

**Comment by IreneVagionakis** [comment]
If you go here http://127.0.0.1:9999/en/inscriptions/iospe-5.14.html, are you able to see the two separate levels of apparatus? (Just to check if the setting has been correctly changed.)

**Comment by IreneVagionakis** [comment]
If yes, it means that the omission in your display is caused again by lacks in the stylesheets, which are not able to render the references to your `<choice>` elements. You could try to remove the `@xml:id` from all your `<choice>`s and all the `<app>`s referring to them; if it still does not work, could you please post here a screenshot of your EpiDoc text+apparatus?

**Comment by LauraNast** [comment]
Yes, I can see the two levels here. I probably missed some aspects and made some mistakes, it is quite complex. I attach the screenshot.
![Schermata 2021-04-15 alle 20 29 47](https://user-images.githubusercontent.com/82391866/114920101-5a412a80-9e29-11eb-9499-c0faf444175b.png)

**Comment by IreneVagionakis** [comment]
I see: `<app>`, `<lem>` and `<rdg>` are elements that should go inside the `<div type="apparatus">`, not inside the `<div type="edition">`.

**Comment by hcayless** [comment]
@IreneVagionakis that may be true for EFES (I'm not sure what level of support for apparatus it provides), but it's not the case for EpiDoc in general, nor TEI. Inline, or "parallel segmentation" apparatus is definitely permissible in an edition div. Papyri.info uses inline `<app>` all over the place.

**Comment by IreneVagionakis** [comment]
You are right, @hcayless, thanks for clarifying it!
I have now checked the other allowed values for the <epidoc-internal-app-style> parameter in EFES (which can be found in webapps/ROOT/kiln/stylesheets/epidoc/README.txt) and apparently the 'ddbdp' value should work also for `<app>`: so, you could try to replace 'none' with 'ddbdp' (instead of 'iospe') at line 86 of webapps/ROOT/sitemaps/config.xmap and see if you get a better result.

**Comment by LauraNast** [comment]
Yes, now it works. Thank you very much!

**Comment by gabrielbodard** [comment]
@hcayless :
> @IreneVagionakis that may be true for EFES (I'm not sure what level of support for apparatus it provides), but it's not the case for EpiDoc in general, nor TEI. Inline, or "parallel segmentation" apparatus is definitely permissible in an edition div. Papyri.info uses inline `<app>` all over the place.

Just for the record, EFES simply imports the EpiDoc Reference Stylesheets (or the latest tagged version) from https://github.com/EpiDoc/Stylesheets, so it supports everything in the EpiDoc XSLT. :) (Which, as you say, includes inline apparatus, with the right parameters turned on. Not in IOSPE-style, however.)

**Comment by Dany71-Che** [comment]
I just tried the solution suggested by Jamie, but I get the same problem with the terminal.

**Comment by kruschwitzp** [comment]
Same for me – still not working, unfortunately.
