### ISSUE TITLE
Patronymics in personal names 

### ISSUE THREAD

**Issue by MhewittOx** [EpiDoc/Tutorials#12]
Sorry to raise another quite specific question!
In an instance where a patronymic is separated from a first name, what would be the neatest way to encode the fact that the patronymic forms part of an individual's personal name? In this example, the patronymic Nauarkhou applies to three individuals, but is only written after the third one. I suppose I could encode it as part of the other two as an abbreviation, though I would not want the patronymic to appear multiple times in the text.
<img width="995" alt="Screenshot 2021-04-15 at 15 32 57" src="https://user-images.githubusercontent.com/79160745/114887527-71b7ed80-9e00-11eb-9cde-61bc7db93b8c.png">

**Comment by gabrielbodard** [comment]
This one is tricky, and happens quite commonly with patronymics, gentilicia, and other names shared by family members. I'm not sure there is a straightforward solution for tagging it in the text itself (overlapping elements and all that). What I would do, I suppose, is just make sure that the Patronymic is included in the name for all three in the Authority List entry for each person.

**Comment by MhewittOx** [comment]
Okay, thanks a lot!
