### ISSUE TITLE
Dimensions of fragmented epigraphs

### ISSUE THREAD

**Issue by Geles-Alonso** [EpiDoc/Tutorials#13]
In the case of fragmented epigraphs (I mean, one inscription is broken in two or more parts not joined together), when including dimensions into the `<supportDesc>`, it is possible to encode the <dimensions> distinguishing the dimension of every single part? Many thanks in advance!!! :-)

**Comment by IreneVagionakis** [comment]
Yes! You can use the `<msPart>` element as shown [here](https://docs.google.com/presentation/d/1uNMmrFgB07ny1br3vgAfhvZ4-Q1wwNWWg7RE-Od7zCg/present#slide=id.g10fffb47e7_0_12) and in the following slides. NB: the `<msPart>` should not go inside `<supportDesc>`, but should include - and so duplicate - at least the entire the `<physDesc>`. If you just want to provide different dimensions for each part without duplicating the remaining data, I think you could have more  `<dimensions>` elements each with a different identifier, but I am not sure if this approach is recommendable: @gabrielbodard, what do you think?

**Comment by gabrielbodard** [comment]
I agree, the formal way to do this is to use `<msPart>`, although this is a little cumbersome. This is how we encoded [IOSPE V 17](https://iospe.kcl.ac.uk/5.17.html), for example, and you can click on "EpiDoc" at the bottom of the page to see the markup.

Encoding all of:

~~~~
<msPart n="1">
  <msIdentifier><idno/></msIdentifier>
  <physDesc>
    <objectDesc>
      <supportDesc>
        <support>
          <dimensions><height>33,5</height><width>20,5</width><depth>6,0</depth></dimensions>
        </support>
      </supportDesc>
    </objectDesc>
  </physDesc>
</msPart>
~~~~

just to record the dimensions may seem like too much, especially if you don't encode any other information about the individual fragments elsewhere in the EpiDoc file. In which case, especially if there are only two or three, I would be happy to use the "less formal" method suggested by Irene—just use multiple `<dimensions>` elements in one `<support>`, and mention in prose that these are the dimensions of the separate fragments.

**Comment by Geles-Alonso** [comment]
Great! Thank you so much!!!
