### ISSUE TITLE
Lost inscription only known by drawing

### ISSUE THREAD

**Issue by Geles-Alonso** [EpiDoc/Tutorials#14]
I would also to know if I could encode in EpiDoc that a lost inscription is know and can be read thanks to a modern drawing. Thanks!!!

**Comment by gabrielbodard** [comment]
Hi Geles: what would you want to record in this edition in addition to (for example), noting in the commentary that the inscription is now lost / was not seen, and the only photograph you give is a picture of the modern drawing? (See for example [IOSPE V 1](https://iospe.kcl.ac.uk/5.1.html).)

I mean, if you wanted you could tag all of the text in your inscription as `<supplied reason="undefined" evidence="previouseditor">`, which is what we would do if a few characters are now lost but previously seen (traditional rendering is usually to underline these characters), but is it really useful to underline an entire text like this? (There may be an argument for consistency, I suppose.)

Is this what you meant?

**Comment by Geles-Alonso** [comment]
Hi Gabby! It is just a stupid doubt I had when encoding the history of an inscription:
<msIdentifier>
<country>United Kingdom</country>
<repository>Now apparently lost (drawing by J. Horsley)</repository>
</msIdentifier>
I wondered if instead of <repository> there is a way to encode in this part of the xml file that we have only a drawing of the inscription. Anyway, it is not really important because I can write this in prose! Many thanks! :-)

**Comment by gabrielbodard** [comment]
It's a good question, and I don't know if anyone has suggested a formal encoding for this information (which might be useful for consistency across a large database). You're saying this in the field `<provenance type="observed">` I take it?

I know some have suggested that "observed" is misleading when you're actually saying you _haven't_ seen it, and suggest "not-seen" or similar instead. And others have put some thought into encoding custodial history in some detail. If you'd like to find out what those people think, ask your question on the [Markup list](https://lsv.uky.edu/archives/markup.html), and I'm sure someone will reply.

**Comment by Geles-Alonso** [comment]
In the message I was refering to the field `<msIdentifier>`. Thanks for the Markup list suggestion!

**Comment by gabrielbodard** [comment]
I see. I suppose "United Kingdom" belongs in `<msIdentifier>` (by TEI standards at least; it's not what epigraphers **or** museum curators would normally call the inscription though, is it?). "Now apparently lost" seems to belong in `<provenance>`, to me though. It's telling us about the history of the object, not its inventory number…
