### ISSUE TITLE
Publication statement and <idno/>

### ISSUE THREAD

**Issue by fra-anthos** [EpiDoc/Tutorials#15]
Hello there! :)

I wonder if the @type I use to identify documents in the section <publicationStmt><idno/> must always be of the same type: most of my texts have a PHI <idno>, but some of them don't. Can I use @type="filename" in these cases, and what does this actually mean in terms of the info I am providing? (am I referring to a file stored in my laptop?) I would like to use standard edition abbreviations and numbers (e.g. SEG 11.52c) but I am not sure it would mean something for Epidoc..

Thanks a lot in advance :)

**Comment by gabrielbodard** [comment]
@fra-anthos : yes, the `<idno type="filename">` should be the primary identifier for this text in your corpus (whether you use an existing nomenclature, or renumber from 1 – 1000, or whatever else you use). For technical reasons we original expected that this string would also be the filename you use for this XML file, although I'm not sure there's any part of the publication or indexing systems that still depends on that.

But you can certainly use other identifiers here, yes: many corpora use multiple `<idno>`s in sequence, with different `@type`s, as for example:

~~~~
<idno type="filename">001</idno>
<idno type="2012-id">1.2</idno>
<idno type="EDH">HD123456</idno>
<idno type="PHI">PH654321</idno>
~~~~

Bear in mind, however, that some of the information captured in values of "EDH" or "PHI" above are probably better encoded in the bibliography, as then they can be used to generate the concordance, etc.
