### ISSUE TITLE
Questions about transcription encoding

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/Tutorials#2]
If you have questions about the encoding of any transcription or “Leiden-like” features in EpiDoc, that you have not been able to answer yourself by reference to the [QuickRef](https://sourceforge.net/p/epidoc/code/HEAD/tree/trunk/guidelines/msword/quickref.pdf?format=raw) or [Guidelines](https://epidoc.stoa.org/gl/latest/), please ask them here and we (or other participants) will try to help.

**Comment by eddiej2410** [comment]
Hi,

In the Leiden and EpiDoc quick reference, '<gap reason="lost" extent="unknown" unit="character"/>' corresponds with 'Lacuna, extent unknown'. However, in a video tutorial ('EpiDoc Tutorial: Greek inscription example'), GB has entered the 'unit' and 'extent' bits in another order, so we have e.g. '<gap reason="lost" unit="line" extent="unknown"/>'. 

My Q: are both combinations for the EpiDoc entries correct?

Thank you!

Eddie

**Comment by eddiej2410** [comment]
Hi,

The EpiDoc entry corresponding with the Leiden expression for a lacuna, the extent of which is unknown, differs slightly from the one entered by GB in the tutorial video (https://www.youtube.com/watch?v=X99YYZoZSl0): the 'extent' and 'unit' components are entered in a different order. Does this matter, or is the key thing here to enter the 'gap' bit first?

Thank you!

Eddie

**Comment by paregorios** [comment]
XML syntax rules permit attributes to appear in any order, but you're right that the element name (in this case "gap") must appear immediately following the initial "pointy" bracket. So, semantically, the following are equivalent:

```xml
<gap extent="5" unit="cm"/>
<gap unit="cm" extent="5"/>
```

but the following would be invalid XML:

```
<extent="5" gap unit="cm"/>
```

**Comment by fra-anthos** [comment]
Hi there! I have a question about XML syntax for verse inscriptions. I have followed the tutorial, but in EFES there is a redundant | at the beginning of my text, I am not sure why. Here is my XML text and the result in EFES:

XML:
<img width="556" alt="Screen Shot 2021-04-12 at 22 26 15" src="https://user-images.githubusercontent.com/82287055/114464804-2625f980-9bde-11eb-9c03-df02a42ac46a.png">

EFES:
<img width="541" alt="Screen Shot 2021-04-12 at 22 17 27" src="https://user-images.githubusercontent.com/82287055/114464587-dba47d00-9bdd-11eb-88b1-56f560ec02ec.png">

Thanks a lot for helping! :)

**Comment by gabrielbodard** [comment]
@fra-anthos This may be a hack, but try moving the first `<lb/>` outside of the opening `<l>`, and see if that makes a difference? (Whether this works or not, this is a transformation issue, and it's a case where you have done nothing wrong in the XML, but there may be an issue with the Stylesheets.)

**Comment by MhewittOx** [comment]
Hi,
I wondered how I can go about making the internal apparatus encoded in my transcription visible through EFES?
Thanks!

**Comment by IreneVagionakis** [comment]
You can edit the `<epidoc-internal-app-style>` parameter at ca. line 86 of webapps/ROOT/sitemaps/config.xmap, replacing the default value 'none' e.g. with 'iospe'

**Comment by EPiette94** [comment]
Hi everyone,
I have a small question concerning the encoding of incomprehensible letters (`<orig>`): I was wondering if it's necessary (or useful) to change the uppercase Greek letters into lowercase. In other words, when I copy the following text which is in uppercase following the Leiden conventions ΑΓΑΛ, can I let it so or do I have to write αγαλ?
Thanks in a advance

**Comment by MartaLegnini** [comment]
Hi everyone!

I'm trying to encode that at least four lines are missing ( _lacuna non minus 4 vv._ in the edition). 
My idea was to use the attribute AtLeast inside the tag gap, without including atMost, like this
`<gap reason="lost" unit="line" atLeast="4"/>`
But in the EFES display, I lose some information, as it looks like this [.. ? ..].
Would I be wrong to assume that the atLeast info could be displayed using a different style sheet? Or is there a better way to do this?

Thanks in advance, Marta

**Comment by IreneVagionakis** [comment]
@MartaLegnini: You are right! The default stylesheets are set to display the `@atLeast` correctly only if there is also an `@atMost`, but your EpiDoc markup is correct.

**Comment by gabrielbodard** [comment]
@EPiette94 :
> I have a small question concerning the encoding of incomprehensible letters (`<orig>`): I was wondering if it's necessary (or useful) to change the uppercase Greek letters into lowercase. In other words, when I copy the following text which is in uppercase following the Leiden conventions ΑΓΑΛ, can I let it so or do I have to write αγαλ?

No, it's absolutely fine to write ΑΓΑΛ in uppercase in the XML. If you don't, the Reference Stylesheets will uppercase it for you, but if you're sure you'll never be interested in displaying the lowercase in any context, then it's fine to write it in uppercase (as well as surrounding it in `<orig>` of course).

**Comment by EPiette94** [comment]
Thank you!

**Comment by gabrielbodard** [comment]
@MhewittOx :
> I wondered how I can go about making the internal apparatus encoded in my transcription visible through EFES?

Irene has answered this, but just to give a bit more detail:

Information on editing this file can be found in the [EFES User Guide](https://github.com/EpiDoc/EFES/wiki/Configuring-EpiDoc-XML-display) on this topic. You can edit the config.xmap file in Oxygen or any other text editor you like. The four values that you can use in place of 'none' are:

* 'iospe' (which will replicate the mini-apparatus for example in [this text](https://iospe.kcl.ac.uk/5.14.html) that we showed in the apparatus video)
* 'ddbdp' (which will replicate the very detailed and lengthy internal apparatus used in the Papyri.info platform ([example text](https://papyri.info/ddbdp/o.bu.njem;;17)))
* 'fullex' (a fairly lengthy app but simpler than ddbdp)
* 'minex' (a fairly minimal app, probably very similar to iospe)

**Comment by fra-anthos** [comment]
@gabrielbodard Thank you! I have managed to get rid of the reduntant | in this way: 
<img width="590" alt="Screen Shot 2021-04-13 at 16 10 34" src="https://user-images.githubusercontent.com/82287055/114576221-d80f0580-9c72-11eb-9a31-5e143c79d5f7.png">

However, I wonder whether this syntax is ultimately wrong and if it would be better to keep the original XML text, even if it displays somehow incorrectly in EFES?

Many thanks! I am having much fun!

**Comment by gabrielbodard** [comment]
@fra-anthos 
> However, I wonder whether this syntax is ultimately wrong and if it would be better to keep the original XML text, even if it displays somehow incorrectly in EFES?

Technically that is wrong, yes (`<lb>` should be at the start of *all* lines). I'm a bit surprised the stylesheets handle this incorrectly, because this is something I have had to do often in the past. I'll try to look into it. But so long as you understand what's going on, and you can both create the output you want and understand what is the best markup in principle, you're fine.

**Comment by eddiej2410** [comment]
Hi, 
sometimes an editor opts to draw strokes (as pictured below). The advice, in this case, seems to be to dot the vertical stroke (doutbful iota) and mention this, along with the diagonal strokes, in the app crit. Presumably, one would extend the lacuna (quantity 29 rather than 28) as well.

Is this the best approach?

<img width="1023" alt="Screen Shot 2021-04-14 at 09 35 49" src="https://user-images.githubusercontent.com/82264567/114680428-16550500-9d05-11eb-95e9-01ba66ec2f9a.png">

**Comment by IreneVagionakis** [comment]
Yes, the best approach is to record this in the apparatus. As for the lacuna length, I'd say that it should remain of 28 characters: if the editor meant that we have a iota which could possibly be a different letter, I'd just have `<unclear>ι</unclear>` followed by a `<gap reason="lost" quantity="28" unit="character">`; if the editor meant that we have apparently a iota followed by the traces of another letter, I'd have - between the iota and the `<gap reason="lost" quantity="28" unit="character">` - a `<gap reason="illegible" quantity="1" unit="character">`

**Comment by eddiej2410** [comment]
Hi, 

I'm unsure as to how best to mark punctuation. My understanding is that <g 

Ἐλπί<unclear>α</unclear><supplied reason="lost">ς εἶπε<g>·</g>

> Yes, the best approach is to record this in the apparatus. As for the lacuna length, I'd say that it should remain of 28 characters: if the editor meant that we have a iota which could possibly be a different letter, I'd just have `<unclear>ι</unclear>` followed by a lacuna of 28 characters; if the editor meant that we have apparently a iota followed by the traces of another letter, I'd have - between the iota and the lacuna of 28 chars - a `<gap reason="illegible" quantity="1" unit="character">`

Thanks!

**Comment by eddiej2410** [comment]
Hi, I'm still a little unclear about how best to mark punctuation... I understand that <g is the requisite element, but when I used this to mark '·', something seemed to go wrong (see below).

<img width="70" alt="Screen Shot 2021-04-14 at 09 57 08" src="https://user-images.githubusercontent.com/82264567/114683322-d5aabb00-9d07-11eb-931c-69170b987483.png">
<img width="115" alt="Screen Shot 2021-04-14 at 09 56 55" src="https://user-images.githubusercontent.com/82264567/114683328-d6435180-9d07-11eb-9d20-07cff2edc17d.png">

**Comment by IreneVagionakis** [comment]
NB: The `<g/>` element is only for the punctuation that was originally present on the stone/papyrus/manuscript, not for the punctuation added by the editor (at it looks to be in your example, but I may be wrong).
As for its display, you should be able to see the dot if switching to the diplomatic edition panel, as the default EFES stylesheets are set to display the symbols in the diplomatic edition and their description in the critical/interpretive edition.

**Comment by IreneVagionakis** [comment]
In any case, the symbol and/or its description **in EFES** are taken or from a list of symbols or from the `@ref` attribute of the `<g>` element, and not from the content of the `<g>` element. So, if you have something like `<g>·</g>`, it won't display anything: you should have instead `<g ref="#·">·</g>` or `<g ref="#·"/>` if pointing to a list of symbols (but you have not started working on the Authority Lists yet, as they are later in our programme), or otherwise just `<g ref="·">·</g>` or `<g ref="·"/>` for the time being.
In all those examples, inside the `@ref` the symbol can obviously be replaced by its description, so here 'upper-dot' (but, if you are not pointing to a list of symbols containing both the symbols and their descriptions, in this case you will have the description displayed both in the critical and in the diplomatic edition).

**Comment by eleonoraselvi** [comment]
Hi everyone! 
My Oxygen often changes the font and size of the Greek text I am writing completely on his own (or at least it seems so). Does someone have an explanation/advice? 
Thanks!

**Comment by MhewittOx** [comment]
Hi, 
I have quite a specific question, the answer to which may well become obvious when I come to indexing - apologies if so!
I am dealing with an instance in which a partially restored personal name is split across two lines, with a variant reading in a previous edition: Δαμοτί- _v_|[μου] (Δαμ[ω]ν[ος] in prev. ed.)

I encoded this as follows: 
![image](https://user-images.githubusercontent.com/79160745/114724565-985c2280-9d33-11eb-9a9c-40ee5c14e96d.png)


Essentially I'm wondering if this makes sense, and particularly whether the personal names will be correctly identified as such? 
Thanks, I hope this is intelligible!

**Comment by camillacampedelli** [comment]
Why do I have only 3 possibilities?
<img width="1280" alt="Bildschirmfoto 2021-04-14 um 16 39 00" src="https://user-images.githubusercontent.com/82399091/114729605-6d2c0000-9d40-11eb-87e4-a89223d8f0f5.png">

**Comment by camillacampedelli** [comment]
I would like to tag Antonius Solemnis as a personal name but I can't find any options
<img width="1280" alt="Bildschirmfoto 2021-04-14 um 16 49 07" src="https://user-images.githubusercontent.com/82399091/114731681-3bb43400-9d42-11eb-8418-59743239b03e.png">

**Comment by IreneVagionakis** [comment]
@MhewittOx: just to be sure to have understood what you did there before answering more broadly, is this bit inside the `<div type="edition">` or in the `<div type="apparatus">`

**Comment by IreneVagionakis** [comment]
@camillacampedelli: you do not have all the choices because your EpiDoc file cannot find the EpiDoc schema, which apparently is not saved in the same folder as your EpiDoc files. The easiest thing to do here is to replace in lines 2 and 3 `href="tei-epidoc.rng"` with `href="http://epidoc.stoa.org/schema/latest/tei-epidoc.rng"`.
After this, you will be able also to markup Antoni Solemnis as `<persName>`.

**Comment by camillacampedelli** [comment]
@IreneVagionakis I'm doing the same steps of the Gabby's video Introduction to Oxygen

**Comment by camillacampedelli** [comment]
@IreneVagionakis ok

**Comment by IreneVagionakis** [comment]
yes, it is fine to replace the link to the online Schema with a link to a local version of the Schema, but you have to check that the Schema (the file that is called tei-epidoc.rng) is saved in the same folder that contains your EpiDoc files, otherwise you have to change the path specified inside `href=""` to match its actual path: I think it is easier just to revert it to a link to the online Schema!

**Comment by camillacampedelli** [comment]
I've used the yesterday's file. I should create a new "muster" but I can't save it:-(
<img width="1280" alt="Bildschirmfoto 2021-04-14 um 17 09 12" src="https://user-images.githubusercontent.com/82399091/114734407-76b76700-9d44-11eb-8f69-fb4ecdb7a7a3.png">

**Comment by IreneVagionakis** [comment]
for downloading the template you should de-select the text, right-click in any point of the page and then select 'Save page as...' (or something similar)

**Comment by camillacampedelli** [comment]
Thanks!

**Comment by gabrielbodard** [comment]
@eleonoraselvi :
> My Oxygen often changes the font and size of the Greek text I am writing completely on his own (or at least it seems so). Does someone have an explanation/advice?

I think what you want to do is set the font and font-size in Oxygen explicitly (unfortunately I think it will use the same font for all text, not just the Greek). In the Oxygen menus, select **Options** --> **Preferences…** --> **Fonts** , and you want to choose settings for the **Editor** font.

If this isn't what you were looking for, please could you send a screenshot of what your text looks like, so we can understand better?

**Comment by eleonoraselvi** [comment]
This is what happens: I write normally and then suddenly (mostly when I start a new line) all the Greek part of the text shifts to a different size/font without me giving any command in this sense. 
Here attached there's a screenshot of how the text looks like after one of these sudden 'shifts'.

![Schermata 2021-04-14 alle 18 05 15](https://user-images.githubusercontent.com/82389568/114742685-44116c80-9d4c-11eb-8f0f-6d85b8afbeda.png)

**Comment by IreneVagionakis** [comment]
This is something that can happen when using a font which is not handling well polytonic Greek: if you change it to Palatino Linotype or to a custom font that you have installed or your computer (e.g. Cardo or New Athena Unicode) your text should stop shifting

**Comment by MhewittOx** [comment]
@IreneVagionakis Sorry, this was under the "edition" div type.

**Comment by gabrielbodard** [comment]
@MhewittOx 
> I am dealing with an instance in which a partially restored personal name is split across two lines, with a variant reading in a previous edition: Δαμοτί- _v_|[μου] (Δαμ[ω]ν[ος] in prev. ed.)

This looks sensible to me. To unpack what's going on in your XML screenshot:

1. you have a string of text that you read/restore as "Δαμοτί[μου]", spanning across two lines. You tag that as a person-reference (and could link that to an internal or external authority list to aid with indexing, for example)
2. a previous editor, Baunack, read that string instead as "Δαμ[ω]ν[ος]", which you have therefore included in an internal apparatus reading. This reading however contains no information about the line-break, nor the fact that it is a person-reference, which is fine so long as you neither need to display nor index this information.

If this is what you were hoping to do, therefore, yes it's all coherent. :)

**Comment by gabrielbodard** [comment]
@IreneVagionakis & @eleonoraselvi :
> This is something that can happen when using a font which is not handling well polytonic Greek: if you change it to Palatino Linotype or to a custom font that you have installed or your computer (e.g. Cardo or New Athena Unicode) your text should stop shifting

Ah, this is something new that Oxygen is doing. (Since I last updated my version of Oxygen 3 years ago anyway.) In some ways it's better than what used to happen which is that if you had a monospaced font that didn't handle polytonic Greek well, any accented character just turned into blank square—but it does mean that you don't immediately see what is causing things to go very weird!

As Irene says, change your default font for the **Editor** (as per my previous reply) to one that you know handles polytonic Greek well, and you should be good.

**Comment by eleonoraselvi** [comment]
@gabrielbodard and @ireneVagionakis
thank you very much for the advice! It seems to be working indeed.

**Comment by Dany71-Che** [comment]
Hallo! I have a problem in encoding a sequence that has been erased on the papyrus. The sequence is 
⟦ε̣ φ̣ ̣ ̣ρ̣τ̣ο̣υ̣ ̣αι ̣⟧
I have encoded as following
`<del rend="erasure"><unclear>ε̣ φ̣</unclear><gap reason="illegible" quantity="2" unit="character"/><unclear>ρ̣τ̣ο̣υ̣</unclear><gap reason="illegible" quantity="1" unity="character"/>αι<gap reason="illegible" quantity="1" unity="character"/></del>`

The Validation error says that attribute unity is not allowed there. I could no find a way to solve the problem. Could you help me? Thank you in advance.

**Comment by Dany71-Che** [comment]
I attach a screenshot of the encoding sequence for my previous question.
<img width="1143" alt="Screenshot 2021-04-15 at 10 01 05" src="https://user-images.githubusercontent.com/82376362/114843783-15d67000-9dd2-11eb-917f-3f654b5b11f2.png">

**Comment by MartaLegnini** [comment]
@Dany71-Che I think you did not close the `<gap>` tag in line 58 (and possibly also repeated it by mistake?)

**Comment by Dany71-Che** [comment]
Thank you! I have closed it, but the message persists.

**Comment by MartaLegnini** [comment]
@Dany71-Che Oh I think you just need to change unity to unit!

**Comment by Dany71-Che** [comment]
Thank you!

**Comment by camillacampedelli** [comment]
This is what I get searching the schema :-(
What is wrong?
<img width="1280" alt="Bildschirmfoto 2021-04-15 um 11 50 27" src="https://user-images.githubusercontent.com/82399091/114850357-f85cd280-9de0-11eb-955a-bd544921576b.png">

**Comment by IreneVagionakis** [comment]
@camillacampedelli: you do not need to open the schema file and edit/search it, it is just fine to have downloaded it and saved it on your computer

**Comment by camillacampedelli** [comment]
I have some questions:
1. Is possible to have a dot like at the end of l. 1 instead ((interpunct))?
2. In the diplomatic transcription I would like to see ANTON and SOLEMN, not ANTON[..] and SOLEMN[I]. Is that possible?
<img width="620" alt="Bildschirmfoto 2021-04-15 um 16 38 30" src="https://user-images.githubusercontent.com/82399091/114888247-57364200-9e09-11eb-8c8f-b31ede90eb05.png">
<img width="626" alt="Bildschirmfoto 2021-04-15 um 16 38 38" src="https://user-images.githubusercontent.com/82399091/114888274-5d2c2300-9e09-11eb-9bd6-b3b06b3f09b0.png">
<img width="620" alt="Bildschirmfoto 2021-04-15 um 16 38 30" src="https://user-images.githubusercontent.com/82399091/114888424-80ef6900-9e09-11eb-999d-ce5881493176.png">

**Comment by IreneVagionakis** [comment]
In the first case you could have it if you were pointing to an authority list of symbols containing both a description and the symbol itself of all symbols. If not, for the time being, you can replace 'interpunct' with the dot itself inside `@ref` (so `<g ref="#·"/>`).

In the second case you will need to adjust the XSLT stylesheets so that they omit all the lacunae in the diplomatic edition.

**Comment by Bea90** [comment]
Hi there, sorry for the very basic question. If I have <l n="1" met="hexameter">
                   `<lb n="1"/>Εὐρύχορος πόλις ἅ<supplied reason="undefined" evidence="previouseditor">δε τεᾶι Νικόκλ</supplied>εες ὁρμᾶι</l>` 
....and I want to tag Νικόκλεες as name, what can I do? .  If I use the tag ''name'' before and after Nicocles Νικόκλεες of course it says that it is wrong because overlap with the tag "supplied". Many thanks

**Comment by emylonas** [comment]
When you are faced with the problem of overlapping elements, you have to pick one to break up. In this case, breaking up the `<supplied>` makes sense. So you could try 
```
<lb n="1"/>Εὐρύχορος πόλις ἅ<supplied reason="undefined" evidence="previouseditor">δε τεᾶι</supplied> <persName><supplied reason="undefined" evidence="previouseditor">Νικόκλ</supplied>εες</persName> ὁρμᾶι</l>
```

with whatever attributes you need on `<persName>`

**Comment by eddiej2410** [comment]
Something is going amiss in the app crit in EFES, and I'm wondering if it's a mistake in the XML. I've tried to encode three separate lines: the first a comment on specific lines, the second a general comment, and the third an alternative restoration.


<img width="740" alt="Screen Shot 2021-04-16 at 11 45 53" src="https://user-images.githubusercontent.com/82264567/115014419-35d96280-9eaa-11eb-8cbb-a533cb765473.png">
<img width="976" alt="Screen Shot 2021-04-16 at 11 45 18" src="https://user-images.githubusercontent.com/82264567/115014449-3eca3400-9eaa-11eb-8988-1660d057df12.png">

**Comment by gabrielbodard** [comment]
@eddiej2410 
> Something is going amiss in the app crit in EFES, and I'm wondering if it's a mistake in the XML. I've tried to encode three separate lines: the first a comment on specific lines, the second a general comment, and the third an alternative restoration.

Yes, the default EpiDoc Stylesheets in EFES are not handling this sort of encoding, as I warned on Wednesday. :) Your encoding looks fine, however. (Except that the third example looks like an alternative reading, not a general comment, but for the purposes of the exercise it's fine.)
