### ISSUE TITLE
Questions about descriptive and historical data

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/Tutorials#3]
If you have questions about the encoding of descriptive and historical features in EpiDoc (“TEI Header” and “Manuscript description”), that you have not been able to answer yourself by reference to the [QuickRefs](https://sourceforge.net/p/epidoc/code/HEAD/tree/trunk/guidelines/msword/structure-cheatsheet.pdf) or [Guidelines](https://epidoc.stoa.org/gl/latest/), please ask them here and we (or other participants) will try to help.

**Comment by fra-anthos** [comment]
Hi there! Not sure I am posting in the right thread, but to me it seems the more appropriate so far. In one of my xtm files I have included some pictures taken from the British Museum. The pictures are licensed under Creative Commons, so I have added the info about the license within my description. However BM seems to require that you add their copywright logo: I have added it in the caption itself; but I still wonder if and how I can get rid of the copywright logo with some mark up. Many thanks!
<img width="1096" alt="Screen Shot 2021-04-14 at 15 53 21" src="https://user-images.githubusercontent.com/82287055/114731555-c17fb180-9d39-11eb-8b71-1fc64c4056f5.png">

**Comment by gabrielbodard** [comment]
@fra-anthos I'm not sure I understand what you mean by the copyright logo—do you just mean the '©' symbol? Or is there a watermark or similar on the photograph that you need to keep? It looks to me that the text you include in `<desc>` there should address any demands the BM might make.

**Comment by fra-anthos** [comment]
Thanks @gabrielbodard! Yes, I meant the portion of the description starting with the copyright logo (© The Trustees of the British Museum). Then I can just live it as it is, thanks!

**Comment by fra-anthos** [comment]
@gabrielbodard Going back to the image topic: is it possible, or even allowed, to use images taken from other (paper) editions? I assume no, for copyright reasons. But perhaps one is allowed as long as she refers to the source publication?

**Comment by IreneVagionakis** [comment]
I'll leave this to @gabrielbodard, but I'd say that it is not allowed (unless the images are under a Creative Commons licence or in the public domain, but it rarely happens in paper editions), because the permissions granted originally by the relevant institutions are generally not transferable.

**Comment by gabrielbodard** [comment]
@fra-anthos : yes, this is probably true. (With the caveat that **I am not a lawyer**!) It seems to me unlikely that a print in a book of an out-of-copyright image (as most photographs of ancient 2D surfaces would be) would be considered to have attracted copyright to that image, so the print would also be out of copyright. In practice many people just do this assuming no one will complain, and no one does, but you should ask for advice from your university's legal office (who will say no!) or publisher (who may be more relaxed) if you want to be safe. Ideally, use a digital image from a source that is reliably labelled as Creative Commons licensed, Public Domain, or copyright-free (e.g. CC0). Wikimedia Commons, Flickr, and even Google Image Search all have options to search for open licensed images.
