### ISSUE TITLE
Questions about indexing or bibliography

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/Tutorials#5]
If you have any questions about tagging items in your EpiDoc file for indexing, search, bibliography, or similar please ask them in this thread. We will try to help with anything that's unclear. Please do feel free to answer questions by other participants if you have come across them yourself already.

**Comment by liviatagliapietra** [comment]
Hi, I am not sure whether my question should go here or in the EFES section - I have created an authority list for persons (listPerson) and a tentative list for locations (monuList) and I have tried to upload them on EFES (by putting them in the "authority" folder and then harvesting and indexing the files). For some reason, I receive a failure message when trying to harvest the monuList, even if the validation with Oxygen is successful; I have been successful with the listPerson, but the prosopography index still does not display anything. What am I doing wrong? Is there some guidance on making authority lists work with EFES I can refer to? Thank you so much!

**Comment by IreneVagionakis** [comment]
Can you post a screenshot of the error message that appears when harvesting the monuList? Are there any whitespaces in its name?
Also in this case a bit of customisation of EFES indices could be needed: the EFES prosopography index by default shows only the `<persName>`s that have a `@key` attribute, so if `@ref` is used instead (as it is recommended for linking to the authority lists) the `<persName>`s are not included in the index.
If you are interested in this, here are the EFES wiki pages about indices and authority lists:
https://github.com/EpiDoc/EFES/wiki/Indices
https://github.com/EpiDoc/EFES/wiki/Authority-lists

**Comment by liviatagliapietra** [comment]
Thank you so much for taking the time to answer my question and for sending the links, Irene! I will definitely have a look at those. Here is the screenshot as you requested:

![Screenshot_2021-04-14 EFES admin RDF harvest result for authority monuList xml](https://user-images.githubusercontent.com/82442029/114728393-f5a5a300-9d36-11eb-8955-0d3ddf90ff55.png)

Yes, I am using `@ref` in `<persName>`s, so that explains why I cannot see them in EFES - is there a way to personalise EFES so that the index shows the `<persName>`s that use `@ref`?

**Comment by IreneVagionakis** [comment]
This is far beyond the goals of this workshop and it requires some knowledge of XSLT, but yes: in the file webapps/ROOT/stylesheets/solr/epidoc-prosopography-index-to-solr.xsl you can replace `@key` with `@ref` at lines 18 and 28 (and after that you have to stop EFES from the Terminal and then restart it).

As for the harvesting, the error message mentions an unexpected `rdf:about` attribute: does it occur inside monuList.xml? If not, it may have to do with the fact that you do not have an index for monuments in EFES yet.

**Comment by liviatagliapietra** [comment]
Thank you very much, Irene. Yes, I know this is beyond the scopes of the workshop - I am sorry for my question. I very much appreciate your answer. I will definitely try to look into this, as I was hoping I could use EFES to check that my authority lists work and that I am able to do the searches I want the final interface of my corpus to be able to make.

No, I do not have any `rdf:about` in the xml file, that is why I got very confused - so it is probably as you said, i.e. this has to do with the fact that EFES does not have an index for monuments. 

Thank you very much again!

**Comment by IreneVagionakis** [comment]
don't apologise at all, I am so happy to see such an enthusiasm for EFES! :)
So yes, I suppose it's that: if you are going to create an index for monuments (now or in the future), let us know if the error goes away after adding it
