### ISSUE TITLE
Encoding stoichedon grid dimensions

### ISSUE THREAD

**Issue by MhewittOx** [EpiDoc/Tutorials#9]
Hi,

I couldn't find anything on this in the EpiDoc guidelines, but I may have been looking in the wrong place. Instead of (or as well as) encoding the dimensions of the letters in an inscription, how would I go about encoding the dimensions of the grid pattern in which they are inscribed, in the case of a stoichedon text?

Thanks!

**Comment by PietroLiuzzo** [comment]
https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-layout.html perhaps?

**Comment by MhewittOx** [comment]
This looks useful, thank you! I'm not sure any of the attributes listed quite denote my meaning, however - I fear that I might overcomplicate things.

**Comment by IreneVagionakis** [comment]
One possible approach for describing the overall stoichedon text is the one suggested by Pietro, that is adding `@columns` and `@ruledLines` attributes to `<layout>` (inside `<layoutDesc>`) for specifying respectively the number of letters per line (even if `@columns` should specifically refer to columns) and rows of the grid.

Another approach could be to use just `@ruledLines` in `<layout>` (if relevant) and to add inside `<handNote>` something like `<dim type="stoichedon">` (or with a slightly different attribute value) for specifying the number of letters per line in a stoichedon text.

If you want to record also the average width of the letters, you can use `<width>` inside `<handNote>`.

As currently there isn't a shared approach for this, it would be interesting to post this question on the Markup List!

**Comment by MhewittOx** [comment]
Great, thank you both for your help! I will post to the mailing list too.

**Comment by gabrielbodard** [comment]
Yes, I would definitely post to Markup. Some people have talked about using `<height type="letter">` vs `<height type="line">`, which might work (with a parallel for width), but maybe there is more specific precedent already.

(For what it's worth I would start by asking: where do you want to print these values in your edition—in layout description? Lettering?—and then decide how best to tag them in there.)

**Comment by emylonas** [comment]
I'd like to add to what Gabby just said. Not only should you be thinking of output and layout, but of how you may want to act on different types of information. For example, if you want to be able to search for inscriptions with a particular number of letters in a line, then it's important to have that marked explicitly. However, you may be more interested in finding all inscriptions that are have a layout type of `stoichedon` regardless of number of letters or lines. It also depends on how many of them you have.
